# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 702d5e95a7c48d29292d9c6e527b970c96de28b490ab03b45991ab45f7210f06dc456eea34030055b665f189882cd69bbf90bdc5c5f6365c885fc9f65f3281b3

test:
  secret_key_base: 2383398c99a06e3fc5ec580bc9eee11925962ef46c411427049b44387bd9f1b14369e0a0a6a70ba86f111867ee05e319fa39935ea3fad89dfaa7413f6e6bd6d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
